# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('spider_class_and_method', models.CharField(default='', max_length=200, verbose_name='爬虫类和方法')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('getting', '正在爬取'), ('end', '爬取结束')], max_length=8)),
            ],
            options={
                'verbose_name': '爬取日志',
                'verbose_name_plural': '爬取日志',
            },
        ),
        migrations.CreateModel(
            name='SpiderLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('model', models.CharField(default='', max_length=30, verbose_name='数据模型')),
                ('status', models.CharField(choices=[('success', '插入成功'), ('fail', '失败，已存在')], max_length=8, verbose_name='爬取状态')),
            ],
            options={
                'verbose_name': '爬虫数据表日志',
                'verbose_name_plural': '爬虫数据表日志',
            },
        ),
    ]
