# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='status',
            field=models.CharField(choices=[('getting', '正在爬取'), ('end', '爬取结束')], default='getting', max_length=8),
        ),
        migrations.AlterField(
            model_name='spiderlogdetail',
            name='status',
            field=models.CharField(choices=[('success', '插入成功'), ('fail', '失败，已存在')], default='success', max_length=8, verbose_name='爬取状态'),
        ),
    ]
