# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20190614_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlogdetail',
            name='spider_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.SpiderLog', verbose_name='爬取日志'),
        ),
        migrations.AlterField(
            model_name='spiderlogdetail',
            name='model',
            field=models.CharField(choices=[('Student', '学生'), ('Class', '班级'), ('Teacher', '教师'), ('ScheduleLesson', '课程表课程'), ('Score', '成绩(名单)'), ('Redio', '教务通知')], default='Student', max_length=30, verbose_name='数据模型'),
        ),
    ]
