# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20190614_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlogdetail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
