# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spider', '0004_spiderlogdetail_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlog',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='status',
            field=models.CharField(choices=[('getting', '正在爬取'), ('end', '爬取结束'), ('error', '爬取异常')], default='getting', max_length=8),
        ),
        migrations.AlterField(
            model_name='spiderlogdetail',
            name='model',
            field=models.CharField(choices=[('Student', '学生'), ('Colloge', '学院'), ('Class', '班级'), ('Department', '教工部门'), ('Teacher', '教师'), ('ScheduleLesson', '课程表课程'), ('Schedule', '课程表'), ('Score', '成绩(名单)'), ('Redio', '教务通知')], default='Student', max_length=30, verbose_name='数据模型'),
        ),
    ]
