# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Timer',
        ),
    ]
