# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20190615_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlog',
            name='type',
            field=models.CharField(blank=True, choices=[('Colloge', '学院'), ('Class', '班级'), ('Student', '学生'), ('Department', '部门'), ('Teacher', '教师'), ('Schedule', '课表'), ('Score', '成绩')], max_length=16, null=True, verbose_name='类型'),
        ),
    ]
