# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_spiderlog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name': '自动更新定时器', 'verbose_name_plural': '自动更新定时器'},
        ),
        migrations.AddField(
            model_name='spiderlog',
            name='task_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('5e3aad5f-2266-4f79-939f-3b1eee945bb6'), verbose_name='第二个的id'),
        ),
    ]
