# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_auto_20190616_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlog',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('7016b009-52d8-4e6b-a412-e1c4660f2f33'), verbose_name='第二个的id'),
        ),
    ]
