# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0011_auto_20190616_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='status',
            field=models.CharField(choices=[('getting', '正在爬取'), ('end', '爬取结束'), ('error', '爬取异常'), ('retried', '已重试'), ('stopped', '已终止')], default='getting', max_length=8, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('dc4d4e3b-713a-4174-a9c6-48bc2d4f39c2'), verbose_name='第二个的id'),
        ),
    ]
