# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_auto_20190616_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='type',
            field=models.CharField(blank=True, choices=[('Colloge', '学院'), ('Class', '班级'), ('Student', '学生'), ('Department', '部门'), ('Teacher', '教师'), ('Schedule', '课表'), ('Score', '成绩'), ('NewScore', '最新成绩')], max_length=16, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('bf152dcd-85f9-4477-9dd2-82ec9ff39561'), verbose_name='第二个的id'),
        ),
    ]
