# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0013_auto_20190616_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('1f013bd8-0033-4c30-8e20-45ba44eb9d03'), verbose_name='第二个的id'),
        ),
    ]
