# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0014_auto_20190617_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('2cba3210-d82b-4f93-990c-1879c4deee02'), verbose_name='第二个的id'),
        ),
    ]
