# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0015_auto_20190617_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('d74414aa-0b5c-4d81-9536-87d79ea602db'), verbose_name='第二个的id'),
        ),
    ]
