# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0016_auto_20190617_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a423b33f-bc92-4cf9-a371-cc4ad0b56dd2'), verbose_name='第二个的id'),
        ),
    ]
