# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0017_auto_20190621_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('5111944b-5e3e-41fb-a155-1fabe7637c6b'), verbose_name='第二个的id'),
        ),
    ]
