# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0019_auto_20190622_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('f02293af-1e69-4095-9fac-037c76cd20c7'), verbose_name='第二个的id'),
        ),
    ]
