# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0020_auto_20190622_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', '专业'), ('Colloge', '学院'), ('Class', '班级'), ('Student', '学生'), ('Department', '部门'), ('Teacher', '教师'), ('Schedule', '课表'), ('Score', '成绩'), ('NewScore', '最新成绩')], max_length=16, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('1b0b4ab7-b636-4c98-bdd5-2b3d3ad3df9f'), verbose_name='第二个的id'),
        ),
    ]
