# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0022_auto_20190622_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderlog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('153ba3d4-77eb-4e6d-8326-cffc8cbac03f'), verbose_name='第二个的id'),
        ),
        migrations.AlterField(
            model_name='spiderlogdetail',
            name='model',
            field=models.CharField(choices=[('Student', '学生'), ('Colloge', '学院'), ('Class', '班级'), ('Department', '教工部门'), ('Teacher', '教师'), ('ScheduleLesson', '课程表课程'), ('Schedule', '课程表'), ('Score', '成绩(名单)'), ('Redio', '教务通知'), ('NewScore', '最新成绩'), ('Major', '专业'), ('MajorLesson', '专业培养方案课程')], default='Student', max_length=30, verbose_name='数据模型'),
        ),
    ]
