# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('users', '0017_auto_20190507_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingJiaoTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='课程名')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('grade', models.CharField(blank=True, choices=[('groupA', '优秀'), ('groupB', '良好'), ('groupC', '中等'), ('groupD', '合格')], max_length=6, null=True, verbose_name='等级')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingjiao_teacher', to='semesters.Semester', verbose_name='学期')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pingjiao_teacher', to='users.Student', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_pingjiao_me', to='users.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '评教老师',
                'verbose_name_plural': '评教老师',
            },
        ),
    ]
