# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_auto_20190508_0046'),
        ('users', '0017_auto_20190507_2100'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pingjiaoteacher',
            unique_together=set([('student', 'lesson_name', 'semester')]),
        ),
    ]
