# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20190508_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingjiaoteacher',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='参数'),
        ),
    ]
