# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20190420_2323'),
        ('subject', '0004_auto_20190508_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', help_text='分词标签', max_length=20, verbose_name='分词标签')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_label', to='lessons.Lesson', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程标签',
                'verbose_name_plural': '课程标签',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessonlables',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lessonlables',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='LessonLables',
        ),
        migrations.AlterUniqueTogether(
            name='lessonlabels',
            unique_together=set([('lesson', 'label')]),
        ),
    ]
