# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190509_1707'),
        ('semesters', '0003_nextsemester'),
        ('lessons', '0014_majorlesson_limit_lesson_minimum_credit'),
        ('subject', '0005_auto_20190508_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepOneLessonTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_one_lesson_teacher', to='lessons.Lesson', verbose_name='课程')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_one_lesson_teacher', to='semesters.Semester', verbose_name='学期')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_step_one_lesson', to='users.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '预选阶段课程教师',
                'verbose_name_plural': '预选阶段课程教师',
            },
        ),
    ]
