# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_majorlesson_limit_lesson_minimum_credit'),
        ('users', '0019_auto_20190509_1707'),
        ('semesters', '0003_nextsemester'),
        ('subject', '0006_steponelessonteacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steponelessonteacher',
            unique_together=set([('lesson', 'teacher', 'semester')]),
        ),
    ]
