# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20190509_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='steponelessonteacher',
            name='post_code',
            field=models.CharField(default='', help_text='表单码', max_length=100, verbose_name='表单码'),
        ),
    ]
