# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0003_nextsemester'),
        ('lessons', '0014_majorlesson_limit_lesson_minimum_credit'),
        ('subject', '0008_steponelessonteacher_post_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steponelessonteacher',
            unique_together=set([('lesson', 'semester', 'post_code')]),
        ),
    ]
