# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190509_1707'),
        ('subject', '0009_auto_20190509_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyXuanKe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(default='专业主干', max_length=20, verbose_name='课程性质')),
                ('point', models.IntegerField(default=0, verbose_name='选点')),
                ('lesson_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_xuanke_me', to='subject.StepOneLessonTeacher', verbose_name='课程教师')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_xuanke', to='users.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课',
                'verbose_name_plural': '选课',
            },
        ),
    ]
