# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190509_1707'),
        ('subject', '0011_auto_20190510_0016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myxuanke',
            unique_together=set([('student', 'lesson_teacher')]),
        ),
    ]
