# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20190510_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='steponelessonteacher',
            name='can_select',
            field=models.BooleanField(default=True, verbose_name='可选'),
        ),
    ]
