# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0013_steponelessonteacher_can_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steponelessonteacher',
            name='can_select',
        ),
        migrations.AddField(
            model_name='steponelessonteacher',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='可删'),
        ),
    ]
