# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_auto_20190510_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='myxuanke',
            name='delete_post_code',
            field=models.CharField(default='', max_length=100, verbose_name='删除表单码'),
        ),
    ]
