# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0015_myxuanke_delete_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steponelessonteacher',
            name='can_delete',
        ),
        migrations.AddField(
            model_name='myxuanke',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='可删'),
        ),
    ]
