# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0016_auto_20190512_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myxuanke',
            name='can_delete',
        ),
    ]
