# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-06 20:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redio',
            fields=[
                ('id', models.CharField(help_text='通知编号', max_length=15, primary_key=True, serialize=False, verbose_name='通知编号')),
                ('title', models.CharField(default='', help_text='标题', max_length=100, verbose_name='标题')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='内容', verbose_name='内容')),
                ('time', models.DateTimeField(default='', help_text='发布时间', verbose_name='发布时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '教务通知',
                'verbose_name_plural': '教务通知',
            },
        ),
    ]
