# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_id', models.UUIDField(default=uuid.UUID('ef2e4d26-4f66-4e71-95e6-fbf4f3b1b697'), verbose_name='第二个的id')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('task_id', models.CharField(blank=True, max_length=70, null=True, verbose_name='任务id')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('class_and_method', models.CharField(default='', max_length=200, verbose_name='调用的类和方法')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('type', models.CharField(blank=True, choices=[('', '毕业生失效'), ('Neo4j', 'Neo4j图数据库')], max_length=16, null=True, verbose_name='类型')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('getting', '正在更新'), ('end', '更新结束'), ('error', '更新异常'), ('retried', '已重试'), ('stopped', '已终止')], default='getting', max_length=8, verbose_name='状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
            },
        ),
    ]
