# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='type',
            field=models.CharField(blank=True, choices=[('Graduate', '毕业生失效'), ('Neo4j', 'Neo4j图数据库')], max_length=16, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('f0b42e66-1079-4a68-81ed-915c62736ada'), verbose_name='第二个的id'),
        ),
    ]
