# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20190621_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('cb11b755-37ab-4b80-bb74-a43ec04f4b51'), verbose_name='第二个的id'),
        ),
    ]
