# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_auto_20190622_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a39a5aae-cb14-4582-8ddc-8217ac5bb29e'), verbose_name='第二个的id'),
        ),
    ]
