# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_auto_20190622_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a5f5adc6-c0a2-499b-86cc-41264d05464e'), verbose_name='第二个的id'),
        ),
    ]
