# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_auto_20190622_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('31cab5da-b1df-40cc-8bbd-3d625e278e60'), verbose_name='第二个的id'),
        ),
    ]
