# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_auto_20190622_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a3b92458-d93d-4300-a990-34a1b228d781'), verbose_name='第二个的id'),
        ),
    ]
