# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '当前学期',
                'verbose_name_plural': '当前学期',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('post_code', models.CharField(default='', max_length=30, verbose_name='表单码')),
                ('verbose_name', models.CharField(default='', max_length=50, verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.AddField(
            model_name='currentsemester',
            name='current_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesters.Semester', verbose_name='当前学期'),
        ),
    ]
