# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '当前学期',
                'verbose_name_plural': '当前学期',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='表单码')),
                ('verbose_name', models.CharField(default='', max_length=50, unique=True, verbose_name='显示名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('if_spider_grade', models.BooleanField(default=False, verbose_name='是否爬取该年级')),
                ('if_spider_semester', models.BooleanField(default=False, verbose_name='是否爬取该学期')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.AddField(
            model_name='currentsemester',
            name='current_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_semester', to='semesters.Semester', verbose_name='当前学期'),
        ),
    ]
