# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsemester',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='currentsemester',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='semester',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='semester',
            name='if_spider',
            field=models.BooleanField(default=False, verbose_name='是否爬取该学期'),
        ),
        migrations.AlterField(
            model_name='currentsemester',
            name='current_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_semester', to='semesters.Semester', verbose_name='当前学期'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='post_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='表单码'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='verbose_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='显示名称'),
        ),
    ]
