# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_auto_20190508_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('next_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_semester', to='semesters.Semester', verbose_name='下学期')),
            ],
            options={
                'verbose_name': '下学期',
                'verbose_name_plural': '下学期',
            },
        ),
    ]
