# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0003_nextsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesters.Semester', verbose_name='对应入学学期')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
    ]
