# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.IntegerField(choices=[(1, '课程班级'), (2, '班级'), (3, '学院'), (4, '专业')], default=1, verbose_name='组织类型')),
                ('group_id', models.CharField(default='', max_length=20, verbose_name='组织id')),
                ('group_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='组织名')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='GroupAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='groups.Group', verbose_name='组织')),
            ],
            options={
                'verbose_name': '组织管理员',
                'verbose_name_plural': '组织管理员',
            },
        ),
    ]
