# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-21 14:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_groupadministrator_if_super'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, verbose_name='组名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_def_group', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '自定义组',
                'verbose_name_plural': '自定义组',
            },
        ),
        migrations.CreateModel(
            name='DefGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('def_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_group_member', to='groups.DefGroup', verbose_name='组')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_group_member', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '自定义组成员',
                'verbose_name_plural': '自定义组成员',
            },
        ),
    ]
