# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-22 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_auto_20190421_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defgroup',
            unique_together=set([('creater', 'name')]),
        ),
    ]
