# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20190422_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='defgroup',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group', verbose_name='对应的群组'),
        ),
    ]
