# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_defgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defgroup',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='def_group', to='groups.Group', verbose_name='对应的群组'),
        ),
    ]
