# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-14 08:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0014_majorlesson_limit_lesson_minimum_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '已点到学生',
                'verbose_name_plural': '已点到学生',
            },
        ),
        migrations.CreateModel(
            name='TheCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_status', models.CharField(choices=[('waiting', '待开启'), ('checking', '正在进行'), ('timeout', '已过期')], default='waiting', max_length=20, verbose_name='点到状态')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('time_limit', models.IntegerField(default=3, verbose_name='几分钟后结束')),
                ('password', models.IntegerField(blank=True, null=True, verbose_name='密码')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_initiate_check', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('schedule_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_check', to='lessons.ScheduleLesson', verbose_name='课堂班级')),
            ],
            options={
                'verbose_name': '点到',
                'verbose_name_plural': '点到',
            },
        ),
        migrations.AddField(
            model_name='checkedstudent',
            name='the_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student', to='checkstudent.TheCheck', verbose_name='点到'),
        ),
    ]
