# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6)),
                ('is_student', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5b66\u751f')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u6559\u5e08')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u73ed\u7ea7\u53f7')),
                ('post_code', models.CharField(default='', max_length=30, verbose_name='\u8868\u5355\u7801')),
                ('name', models.CharField(max_length=70, verbose_name='\u73ed\u7ea7')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u7ea7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Colloge',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='\u5b66\u9662\u53f7')),
                ('post_code', models.CharField(default='', max_length=30, verbose_name='\u8868\u5355\u7801')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u5b66\u9662\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u9662',
                'verbose_name_plural': '\u5b66\u9662',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u5355\u4f4did')),
                ('name', models.CharField(max_length=35, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('post_code', models.CharField(default='', max_length=30, verbose_name='\u8868\u5355\u7801')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6559\u5de5\u5355\u4f4d',
                'verbose_name_plural': '\u6559\u5de5\u5355\u4f4d',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(default='', max_length=10, verbose_name='\u4e13\u4e1a\u53f7')),
                ('post_code', models.CharField(default='', max_length=20, verbose_name='\u8868\u5355\u7801')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u7ea7')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u4e13\u4e1a\u540d\u79f0')),
                ('training_objectives', models.TextField(blank=True, default=None, null=True, verbose_name='\u57f9\u517b\u76ee\u6807')),
                ('basic_knowledge', models.TextField(blank=True, default=None, null=True, verbose_name='\u57fa\u7840\u77e5\u8bc6')),
                ('major_knowledge', models.TextField(blank=True, default=None, null=True, verbose_name='\u4e13\u4e1a\u77e5\u8bc6')),
                ('direction_introduction', models.TextField(blank=True, default=None, null=True, verbose_name='\u65b9\u5411\u4ecb\u7ecd')),
                ('subject', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='\u96b6\u5c5e\u79d1\u7c7b')),
                ('main_subject', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='\u4e3b\u5e72\u5b66\u79d1')),
                ('similar_major', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='\u7c7b\u8fd1\u4e13\u4e1a')),
                ('education_background', models.CharField(blank=True, default='\u672c\u79d1', max_length=10, null=True, verbose_name='\u5b66\u5386')),
                ('degree', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6388\u4e88\u5b66\u4f4d')),
                ('length_of_schooling', models.IntegerField(default=4, verbose_name='\u6807\u51c6\u5b66\u5236(\u5e74)')),
                ('minimum_graduation_credit', models.IntegerField(default=160, verbose_name='\u6700\u4f4e\u6bd5\u4e1a\u5b66\u5206')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('if_multiple_directions', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u591a\u4e2a\u65b9\u5411')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a',
                'verbose_name_plural': '\u4e13\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='\u5b66\u53f7')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6, verbose_name='\u6027\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('cla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Class', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8003\u751f\u53f7')),
                ('nationality', models.CharField(default='\u6c49\u65cf', max_length=30, verbose_name='\u6c11\u65cf')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('political_status', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u653f\u6cbb\u9762\u8c8c')),
                ('birthplace', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7c4d\u8d2f')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u901a\u8baf\u53f7\u7801')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('base_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='\u57fa\u672c\u4fe1\u606f')),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Class', verbose_name='\u73ed\u7ea7')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u8be6\u7ec6\u4fe1\u606f',
                'verbose_name_plural': '\u5b66\u751f\u8be6\u7ec6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u6559\u53f7')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6, verbose_name='\u6027\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08',
            },
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together=set([('major_id', 'grade')]),
        ),
        migrations.AddField(
            model_name='class',
            name='colloge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Colloge', verbose_name='\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Major', verbose_name='\u4e13\u4e1a'),
        ),
    ]
