# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='basic_knowledge',
        ),
        migrations.RemoveField(
            model_name='major',
            name='major_knowledge',
        ),
        migrations.AlterField(
            model_name='major',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6388\u4e88\u5b66\u4f4d'),
        ),
        migrations.AlterField(
            model_name='major',
            name='education_background',
            field=models.CharField(blank=True, default='\u672c\u79d1', max_length=50, null=True, verbose_name='\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='major',
            name='main_subject',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u4e3b\u5e72\u5b66\u79d1'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u4e13\u4e1a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='major',
            name='similar_major',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u7c7b\u8fd1\u4e13\u4e1a'),
        ),
        migrations.AlterField(
            model_name='major',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u96b6\u5c5e\u79d1\u7c7b'),
        ),
    ]
