# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studentdetail_cla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='id_card',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u901a\u8baf\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='political_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u653f\u6cbb\u9762\u8c8c'),
        ),
    ]
