# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190325_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u901a\u8baf\u53f7\u7801'),
        ),
    ]
