# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190402_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
    ]
