# Generated by Django 2.1.5 on 2019-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190402_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='colloge',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.Colloge', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cla',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='base_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Student', verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
