# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190409_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=70, verbose_name='班级名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(help_text='学号', max_length=12, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', help_text='姓名', max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
