# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190411_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='base_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='基本信息'),
        ),
    ]
