# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
