# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-30 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190415_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
