# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', help_text='密文密码', max_length=100, verbose_name='密文密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('the_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_password', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对称加密密码',
                'verbose_name_plural': '对称加密密码',
            },
        ),
    ]
