# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_mypassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypassword',
            old_name='the_user',
            new_name='user',
        ),
    ]
