# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190508_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cla', to='users.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='users.Class', verbose_name='班级'),
        ),
    ]
