# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190610_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在读'),
        ),
    ]
