# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f56d0874-03ac-4f78-817d-bb03a3da43b9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('aef96cd7-f626-41ae-9f25-9c6f685ef2d5'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94b72648-a528-4aef-b478-765475dd25cf'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='name',
            field=models.CharField(max_length=20, verbose_name='拓展名'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d70f786b-5a75-4d94-9767-6b89d127498a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4991828d-03f5-4b93-9ceb-bfd84489b288'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6e86fd0-7396-4c4b-9723-e39b9e81a4c5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('3f68c5a7-0923-4f38-a566-a98f702cec5e'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6cc5b1f6-194c-457a-aaa0-1349ec864c81'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterUniqueTogether(
            name='fileextension',
            unique_together=set([('name',)]),
        ),
    ]
