# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_auto_20190608_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1db680c4-1649-4bc8-ad25-00252a81ea7a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('953d4cc2-e91b-4d4f-80fa-a038ddebbffa'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3beaa942-fdd5-46cc-a041-ed3f42cd3562'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30951422-d724-4ad4-b7c5-a47460e9ec05'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0415e115-e8f3-4166-9ce6-5936c8b65cc0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('010a0c5d-ec68-490d-8241-f68098324527'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('dd40b2b9-ca72-493e-b9f3-9672e40f2738'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16e0ff32-6434-4991-b179-5bb9efb76d09'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterUniqueTogether(
            name='fileextension',
            unique_together=set([]),
        ),
    ]
