# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0003_auto_20190608_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79739dd7-05d7-4b41-adeb-838db88f077a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('878be063-6a15-44ac-82e1-e04f6add43f3'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('520cf7c4-7543-4887-a418-84704d72627e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='拓展名'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('070e8999-c256-49fd-b123-280b97d28d15'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9d84312-f806-4a29-ba0b-c7a08066565d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29209727-ac93-4cfc-a831-c565f8488883'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('6584ab4d-6f9b-48d3-8c8d-672b24ecf49f'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10f3dfe9-6f2a-45e5-b07f-df0c580012e4'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
