# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0004_auto_20190608_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b8b1353-260e-4d97-9b14-31ad2fc33606'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('5b09c1dc-2bbc-4e11-9b3f-94e4155c8cb2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ce1dc62-0d84-4f7d-81e7-f50bf700711d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4716e2ce-292c-491a-9aee-dd65d523af43'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('633943ea-470a-43a0-92e9-779d40cf3efc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df637239-6bb6-4372-a64a-c631bab1877f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('4fd89762-0093-4136-af94-7c0ad448599c'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0251fb32-0dd3-4daa-b399-b89ed7c89631'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
