# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0005_auto_20190609_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64ea7905-79ac-4dd2-82b6-9faf264a33fb'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('46565a58-c4db-479f-b887-872162639554'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14139baf-9288-404e-b2ea-80fcbb8ef8c6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44a884b2-3067-421b-aee0-48e5a65872f1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3786c79-521d-481a-addc-f158dc87195e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb0a0232-8aa4-45d7-b5c4-88e6121a6c1a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('f5c07041-6a11-4c28-bdad-dd118fe71232'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9dc49e80-41b4-49ac-919a-877d292d62ec'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
