# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0006_auto_20190609_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('121884de-3ccf-43d2-a175-2576ffe7a45a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('1ceb3239-449a-4ec8-b9bb-6cd5f23b0cd3'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbcba2fa-7fd3-4071-a0bc-3e924634cc8a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a6b6568-a468-4c04-9427-5998a059565e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ed74b0a-416c-4dd4-8269-ef71b761776a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59b96108-ff2c-4d91-b44f-af19c05cbcba'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a3db90da-a846-4d4f-85be-25eb8707d347'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5324c755-6a00-44b3-b40a-16ccae2a8dc1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
