# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0007_auto_20190609_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34b348e6-1003-4a62-acdb-dbbe1491e107'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('973bc28e-da71-4fa3-81f1-c35c4f5581ab'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a4b799f-c373-4527-b63b-a8ca3d99c20e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f02c848-ae1f-4219-8dac-fedfffa65c8b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3e4609c-7684-42fc-ad1e-e58b3b6c71af'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dcfd8384-f3d7-47fb-b41b-89ce1f095f9d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('95294fe1-c0a0-445c-ba1f-c68bf06d349f'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('183f9a59-af2b-45e6-b033-4c380eee04b1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
