# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0008_auto_20190610_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb000f0b-109e-4b51-a4c5-85d8d095a2fe'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('86547465-cfaf-4dee-b6ee-1de1c6e96d67'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3968f994-fe28-4d37-ae20-cde3f8242527'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9827f62f-3681-4878-b7c5-e3eb1bc7e90f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('682ee314-9d9d-434a-84f8-d0c71e943bec'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c29cdb5c-941b-4c71-adf4-868a41120fa7'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('af276abb-c265-409c-8264-e05bbdf08d81'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20105fec-c0d2-4b22-8a6d-36b54bf08fec'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
