# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0010_auto_20190610_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86dc6d60-d624-4b00-89aa-d2eb9fea1f6f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('fec6cf01-1b2e-4bc8-a180-740687802650'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6827b3a-5664-47a3-a7d0-5c55a759de94'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b46c8dcc-3be2-4e4f-a685-3254204cdb3d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15a7e2a6-6c59-4a77-af92-22a8b782fdf5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f607d164-d639-4e64-9686-f0e939eca56a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('1f7a0b0e-68e4-4f7b-8629-7a0d464ac6c4'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c0a07b3-d3f3-4db5-a579-2d5c014cfa4a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
