# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0012_auto_20190611_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c846fedd-983f-42ad-a6e0-e358a42c618d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('8a254bbf-1709-4e59-86b1-08d2ca69e145'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ffffe4b-8fba-41aa-b2d7-a02886c9e2a6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8998de4f-a876-4df0-9d10-209d3094b42a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1047ce3e-d3cd-467b-9e0a-d00ca828362f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19ea1ae3-1f6d-4924-8513-0d0c184351b0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('cf639d98-39bd-4162-b282-22635e5a27ca'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10d6fa06-1d47-4c53-ae16-cf877e5f0edd'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
