# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0013_auto_20190614_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a52ce596-8c7a-4293-8a9b-01e1fd30d709'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a5013ea2-48b9-4f2b-a39c-2de904efe0d9'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7074ba53-ca51-45be-a323-7f6e23cc166e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edcdf5b8-71ea-4cd5-8b6e-21eafe0cb2b0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e9c60c8-5737-43b6-b253-676857dc724f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f70a0008-cb45-4e29-97ec-9d37e22683e5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('8a15bb50-7673-4559-82bf-f042c1fdce47'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('96595265-c6ec-40c4-be93-697e27ce30e9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
