# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0014_auto_20190614_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0a866a0-38c4-43cf-9e4c-b2e57f0f46cd'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('b5660426-8036-489e-9f0f-5ea0615a4ea8'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f5f2de8-d407-436e-af88-1886f400e0a9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2dd6cd5a-bea4-4ab1-bbf6-0fcdb955faf2'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21cc7884-d893-40cd-b66e-281efda69e01'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e909926-8291-4cad-98f8-6971f76e72d7'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('ffe63783-77e2-4d1b-bf7d-4d47394028f5'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d155eb83-6188-4448-90da-d2a315c73642'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
