# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0015_auto_20190614_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d5c7a87-cb28-47ae-8069-4aade55dca07'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('311b4021-21d4-44c3-a76f-d690f65a42f6'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63ed35c1-6cee-4202-bc09-8fbe7236f1d2'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02972eab-9bd4-4185-8d7d-0f6fdfbc52bc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('523a3398-f45a-4366-8057-24f9ba098e50'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83026089-5424-46e4-b772-cdf71b573a94'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('d1d12953-fffe-47ee-8e13-0f12a3c78dff'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3ed3038-6bc1-466c-a72d-07ecd4ca98b2'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
