# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0016_auto_20190614_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bebd986d-4ae6-4822-b9cf-a1c6ac6fc367'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('ec6a021c-d3f8-48d2-9f64-a84a092660eb'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf4e1d03-968d-4c58-a3b7-9d0070e5b371'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5385541b-4d0d-4136-9489-2846f43f4d9d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29150cfd-5649-4e4a-a48b-0506bf5693a1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7ddf359-4d6c-4726-b2e6-7608fdeca949'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('12ff709e-1b10-4563-a902-6f397fa729b2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca332798-5d25-43d5-a401-c2043f0ff813'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
