# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0018_auto_20190615_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6612342d-a74d-405b-8d15-ce3f74541fcb'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('025c2efa-9e80-4aa1-b7f3-0cb508cc099f'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc26f03e-2066-4a5d-a31a-f03372cce27f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db39a4c8-7b1a-4880-921a-f7a0b94911f3'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7db5e41-52b2-4ce1-a30c-d7a2fa9c5c97'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c302a394-ab5a-4b11-97bb-c9f7b7c546a5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('2a1c601a-98fa-42c5-b507-43ce33cc3511'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3aa393fb-b59d-49eb-a119-abd49448d81d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
