# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0019_auto_20190615_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ddba692-a65d-4fb4-93aa-fd330851452e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('de1bbe73-949a-4b27-8d4c-1acfa11839e9'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('603496a7-27ff-45a2-8975-b1e56d57feb0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52a17f31-e5d4-4884-b107-7af9ede7ef86'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('435329ca-701c-465c-935b-4a56eebec606'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce372bbe-ce9a-4719-bcd1-0365738a3c78'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('1cc09565-85ae-4cac-b556-c88da856d34b'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('676cf797-a8db-4ff8-b0f2-2fcd3e73f36d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
