# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0020_auto_20190615_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe724033-d399-415e-a3fd-de5aa98f073b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('a4efd9b6-6826-4d7f-8cea-98f130cebb31'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cd65ad7-0ac7-4c15-ba18-7f8a0ed6bf99'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51ede5c9-5e4c-45c7-be6a-97728ea2f3eb'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5271c551-f522-49aa-9e36-7a26bd65f298'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bffcc841-6da6-41de-96db-268102f55ea6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('6b89c34a-d404-4ba3-8d13-32cfae05dae2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2766426e-1514-4374-8d2d-e70e5cb2e812'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
