# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0021_auto_20190615_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('373b2afb-bb21-42e0-9d8f-a9583831bd09'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('9dfff650-71ca-4371-9b28-66215ab212d6'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92ce1d8f-f043-43df-91cb-1ef3da1c0ecc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21ec228e-2a05-4423-89c5-bf6229eab1e5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d121dc3-25a9-43da-bcb3-cfe4748de317'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72460d7f-dd06-47c5-9661-820d9f99d8f9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('d5b67d63-2c42-4e90-ac59-562011dd5570'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('077f4445-ace8-47b2-95bb-9ee9d73b0a85'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
