# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0022_auto_20190615_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('171e9a23-800d-4133-a249-c7217e17f92a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('6cc456a8-6075-4303-809e-250b643d67bd'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a4bbc8c-8feb-4a5d-ae0c-b0664c5b1da7'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5b3e4ab-17bd-4093-aa95-8c61edc2b0c5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b6633e4-ab87-4366-81b4-cb7c19ad112b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e16bdb74-46e4-45d9-a421-8aee80251c64'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('710b85dc-30b1-4bc9-b2fd-66b08c60a010'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c8d67ac-7da5-4e66-ade0-add2283d83ec'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
