# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0023_auto_20190615_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a8f329a-e6a9-48ef-8d7b-97bc8aa08557'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('e1098715-6566-41d8-99d1-9035394e8c1a'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b253dd7-e3ad-4e64-8b19-507aa1f20107'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ba4c22a-5476-47d9-b2df-0094b451675a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('640eeb3f-5462-446f-8b8a-439bc0f2d14d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('070dd779-2227-4005-9b18-058e33918e1e'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('9833f767-d2a8-43ee-922d-4f160ec59fce'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a6c3690-a12e-4894-aae6-a76072e43aba'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
