# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0025_auto_20190616_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec390b3b-3a03-4b0f-b6c0-9ae70c082726'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('471ba4b2-b373-468f-9e24-14ac7092ef2a'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93ce2383-10db-47ab-9e4b-a2f2d2935314'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92638539-1785-47eb-ab09-4da8e00912ae'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fbcd9a9-ecf3-457e-91c1-7d6e34fccf81'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('676399ec-dc7f-46ad-beb4-7706efb7eff8'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('ee4c7986-d01a-41bc-8292-22791999b90d'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b403f900-bc46-4635-a2bf-ea3d05fec482'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
