# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0026_auto_20190616_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17dd2e48-238e-4a09-a383-1895d453f5da'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('c4ae4524-a2fa-4ca6-8245-7d34a65cbe0c'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f0059c2-932b-469f-8a91-83555c90ada7'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2014b215-49ec-4da6-a071-1606be1048c4'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e84175b-e98a-470c-a07c-aede8708ecb2'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7b2b501-9792-431d-983f-ff535f5a06fb'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('6fb46b8e-5b32-40f8-9520-5afeef34196e'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('699808d3-7224-4096-b194-ff528bddf5ad'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
