# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0027_auto_20190616_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('117e2487-c966-42b9-8941-d73251e72a8f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('ffceee92-f569-4492-8b7b-0e5a14832804'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('221e919e-f172-487a-83bb-97f1681267d6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac2df9a3-090d-4cb1-99f9-07fba96c6daa'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f17042da-7d63-40c6-b09b-4700fa4c5441'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fc182ce-8370-49e4-a9a6-5c703532e8d5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('092c0289-3582-4f3d-a2bc-f6a956bbe1cd'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a529e69-0ad4-4005-bd70-926aee9dc9ce'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
