# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0030_auto_20190617_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f883738-7788-45c3-85fe-8b5109c0b660'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('782186e8-b49e-4097-8a6d-ba14cc6f06a2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f395180b-9ab4-49f6-8091-faa68bdbb0ff'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a50e8c7-ad28-4431-948b-a7bd6c84ced5'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('758ceec4-cd24-42c5-8f1f-0082e515844b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8c2ac0c-356b-4b9e-abbe-682b67a1bb63'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('58c9ab2a-e41e-4bbf-8a9e-11daef8c4c20'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d0d2e36-5487-4f70-8d32-f64676a152cd'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
