# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0031_auto_20190621_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61ad594b-92be-4638-90fe-bf3c5ac6e165'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('5434ddf2-5db3-45f8-aba1-825fe07569f2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d6dd4d6-fdfe-496c-bc30-6bd1a4af6b2a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0183016-d32d-4439-b2fb-0030e1ffdf5a'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c1b186a-8155-481a-9517-e987126dceb6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53b907bc-0bfd-4296-adbb-7ca2d550bb8b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('d5bb802f-d79e-4100-8da7-9b5d7e86afa2'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75addcc8-656c-4eb4-9740-367c39866273'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
