# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0032_auto_20190621_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d89a1cbb-9bf0-473f-8564-f73a7d80c192'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('bc5f8f37-9f17-4988-964f-04c1909552ad'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('001d64bb-ba5e-423e-98b8-93121fcb97dc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aaacf9a7-3f69-425c-aa1a-6b1e614cd22f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66a5ec1a-15f9-4f03-866a-f5876660cfc7'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e72050f-e37b-45c0-85dd-e07334389eb8'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('6684ab9c-1a06-44e1-ad62-e5333fab548e'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('116f8845-4f2d-4bed-95b8-08d89f385950'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
