# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0034_auto_20190622_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8eea9cf5-5cb4-4cd8-a3e5-88c4ddb36f65'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('53eef01f-f7b6-4889-9e23-96f3a1d39b14'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f2033ee-427f-4c3e-9d5d-f83f64ff14cc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ffbbf24-099b-4a64-b6cf-1089519cbb53'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8febccb-6ff5-4cd1-ae52-9f788617f799'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df5db4d4-c3b7-424f-b561-eb0df4049d0f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('8527fe44-ef35-440b-8751-ac626294f8c7'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97272a55-8b1a-485a-9d29-29f81e2145c0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
