# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0035_auto_20190622_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('827a96e8-6f3a-464b-83b9-be2fb15195d1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('5012f6bc-f72d-4800-a929-d4fafd88347d'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38699117-a172-4159-8f2a-424d08c33ce3'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d80821a-7ae9-4b05-bc7f-0cfbe815b5a9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ef1105e-acd8-4e2d-9b89-4cc9aee1f4f9'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e21564b8-aaff-4c08-9832-09d0444d0b65'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('93565453-c2d7-4e7a-9a01-2dedee067b05'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('334212d1-ae6f-4846-81e0-4fdd1764cf3c'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
