# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0036_auto_20190622_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d36b84d-c9d7-42d6-b1c2-fa40a12528d4'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('447ebac1-eeaf-46b1-8a21-b0b0af1a49ad'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c446f566-ea7d-4c39-9066-5e66692fa169'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea248e04-82b3-4891-abe2-f4f093e635b0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ed5a49f-9fa5-4ce4-aa5b-420f75e3f483'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca7bb51b-e175-4a89-85be-25192ada46c1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfile',
            name='verbose_id',
            field=models.UUIDField(default=uuid.UUID('84677e20-2f4e-46f3-81d1-8ed9b7cf61f4'), verbose_name='用于下载的id'),
        ),
        migrations.AlterField(
            model_name='sharelinkfolder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a3c8170-70e2-4934-979f-fd0c87470f76'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
