# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-04 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='', verbose_name='ip')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('action_type', models.CharField(choices=[('match', '查询'), ('delete', '删除'), ('create', '增加'), ('update', '更改')], default='', max_length=6, verbose_name='操作方式')),
                ('message', models.CharField(default='', max_length=200, verbose_name='操作内容')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_log', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
    ]
