# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('match', '查询'), ('delete', '删除'), ('create', '增加'), ('update', '更改'), ('other', '其他')], default='', max_length=6, verbose_name='操作方式'),
        ),
    ]
