# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='id',
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(default='', primary_key=True, serialize=False, verbose_name='ip'),
        ),
    ]
