# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20190504_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='adcode',
            field=models.CharField(default='', max_length=10, verbose_name='行政编码'),
        ),
        migrations.AddField(
            model_name='ip',
            name='rectangle',
            field=models.CharField(default='', max_length=100, verbose_name='经纬度'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
    ]
