# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-06 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20190504_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间'),
        ),
    ]
