# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='knowledge_labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit', to='homeworks.KnowledgeLabel', verbose_name='知识点标签'),
        ),
    ]
