# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_auto_20190617_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='knowledge_labels',
            field=models.ManyToManyField(blank=True, related_name='unit', to='homeworks.KnowledgeLabel', verbose_name='知识点标签'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lesson_file',
            field=models.ManyToManyField(blank=True, related_name='unit', to='disks.File', verbose_name='章节课件'),
        ),
    ]
