# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_auto_20190617_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonperiod',
            name='lesson_file',
            field=models.ManyToManyField(blank=True, related_name='lesson_period', to='disks.File', verbose_name='课时课件'),
        ),
        migrations.AlterField(
            model_name='lessonperiod',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='lesson_period', to='homeworks.Unit', verbose_name='章节'),
        ),
    ]
