# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-10 15:07
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20190410_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '系统通知'), (2, '作业通知'), (3, '普通消息'), (4, '教务通知')], verbose_name='消息类型')),
                ('title', models.CharField(default='', help_text='标题', max_length=100, verbose_name='标题')),
                ('body', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='消息内容')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('receiver', models.ForeignKey(blank=True, default=None, help_text='接收人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_message', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('receiver_class', models.ForeignKey(blank=True, default=None, help_text='接收班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_message', to='users.Class', verbose_name='接收班级')),
                ('sender', models.ForeignKey(help_text='发送人', on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
