# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-21 12:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_groupadministrator_if_super'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReceiverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='阅读时间')),
                ('if_delete', models.BooleanField(default=False, verbose_name='是否回收')),
                ('if_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('if_report', models.BooleanField(default=False, verbose_name='是否举报')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('receiver', models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '接收组接收人消息',
                'verbose_name_plural': '接收组接收人消息',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '系统通知'), (2, '作业通知'), (3, '普通消息'), (4, '教务通知'), (5, '通知回复')], default=3, verbose_name='消息类型')),
                ('title', models.CharField(default='', help_text='标题', max_length=100, verbose_name='标题')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='消息内容')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('send_state', models.IntegerField(choices=[(0, '草稿'), (1, '发送')], default=1, verbose_name='发送状态')),
                ('if_report_over', models.BooleanField(default=False, verbose_name='是否被举报过度')),
                ('if_delete', models.BooleanField(default=False, verbose_name='是否回收')),
                ('if_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('reply_message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='父消息')),
                ('sender', models.ForeignKey(help_text='发送人', on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=70, verbose_name='文件名')),
                ('file', models.FileField(upload_to='uploads_file/%Y/%m/%d', verbose_name='文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='message.Message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息文件',
                'verbose_name_plural': '消息文件',
            },
        ),
        migrations.CreateModel(
            name='ReceiverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='groups.Group', verbose_name='组织')),
                ('message', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='message.Message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息接收组',
                'verbose_name_plural': '消息接收组',
            },
        ),
        migrations.CreateModel(
            name='ReceiverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='阅读时间')),
                ('if_delete', models.BooleanField(default=False, verbose_name='是否回收')),
                ('if_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('if_report', models.BooleanField(default=False, verbose_name='是否举报')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='message.Message', verbose_name='消息')),
                ('receiver', models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '接收人消息',
                'verbose_name_plural': '接收人消息',
            },
        ),
        migrations.AddField(
            model_name='groupreceivermessage',
            name='receiver_group',
            field=models.ForeignKey(blank=True, help_text='接收组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_receiver_message', to='message.ReceiverGroup', verbose_name='接收组'),
        ),
        migrations.AlterUniqueTogether(
            name='receivermessage',
            unique_together=set([('message', 'receiver')]),
        ),
        migrations.AlterUniqueTogether(
            name='receivergroup',
            unique_together=set([('message', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='messagefile',
            unique_together=set([('file', 'message')]),
        ),
    ]
