# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-22 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update_time',
        ),
    ]
