# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20190410_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='阅读时间')),
                ('if_delete', models.BooleanField(default=False, verbose_name='是否回收')),
                ('if_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
            ],
            options={
                'verbose_name': '接收人消息',
                'verbose_name_plural': '接收人消息',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_class',
        ),
        migrations.AddField(
            model_name='message',
            name='if_destroy',
            field=models.BooleanField(default=False, verbose_name='是否销毁'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='回复消息'),
        ),
        migrations.AddField(
            model_name='message',
            name='report_time',
            field=models.IntegerField(default=0, verbose_name='举报次数'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_state',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '发送')], default=1, verbose_name='发送状态'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='receive_message', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
