# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190411_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='回复消息'),
        ),
    ]
