# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190411_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='if_destroy',
        ),
        migrations.AlterField(
            model_name='receivermessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_message', to='message.Message', verbose_name='消息'),
        ),
    ]
