# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20190411_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=70, verbose_name='文件名')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d', verbose_name='文件')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='message.Message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息文件',
                'verbose_name_plural': '消息文件',
            },
        ),
    ]
