# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_messagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='父消息'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, '系统通知'), (2, '作业通知'), (3, '普通消息'), (4, '教务通知'), (5, '通知回复')], verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(upload_to='uploads_file/%Y/%m/%d', verbose_name='文件'),
        ),
    ]
