# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20190411_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='message.Message', verbose_name='消息'),
        ),
    ]
