# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20190411_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='if_collect',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AddField(
            model_name='message',
            name='if_delete',
            field=models.BooleanField(default=False, verbose_name='是否回收'),
        ),
    ]
