# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20190411_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivermessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.Message', verbose_name='消息'),
        ),
        migrations.AlterField(
            model_name='receivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
