# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190411_1428'),
        ('message', '0011_auto_20190411_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Class')),
            ],
            options={
                'verbose_name': '接收班级',
                'verbose_name_plural': '接收班级',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='receivermessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.Message', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='receiverclass',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='receiver_group',
            field=models.ForeignKey(blank=True, help_text='接收班', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.ReceiverClass', verbose_name='接收班'),
        ),
    ]
