# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20190412_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivermessage',
            name='receiver_group',
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='receiver_class',
            field=models.ForeignKey(blank=True, help_text='接收班', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.ReceiverClass', verbose_name='接收班级'),
        ),
        migrations.AlterField(
            model_name='receiverclass',
            name='cla',
            field=models.ForeignKey(help_text='班级', on_delete=django.db.models.deletion.CASCADE, to='users.Class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='receiverclass',
            name='message',
            field=models.ForeignKey(help_text='消息', on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='消息'),
        ),
    ]
