# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20190409_1009'),
        ('message', '0013_auto_20190412_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverLessonClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson_class', models.ForeignKey(help_text='课程班级', on_delete=django.db.models.deletion.CASCADE, to='lessons.ScheduleLesson', verbose_name='课程班级')),
                ('message', models.ForeignKey(help_text='消息', on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '接收班级',
                'verbose_name_plural': '接收班级',
            },
        ),
    ]
