# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_receiverlessonclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivermessage',
            name='receiver_lesson_class',
            field=models.ForeignKey(blank=True, help_text='接收课程班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.ReceiverLessonClass', verbose_name='接收课程班级'),
        ),
        migrations.AlterField(
            model_name='receivermessage',
            name='receiver_class',
            field=models.ForeignKey(blank=True, help_text='接收班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive', to='message.ReceiverClass', verbose_name='接收班级'),
        ),
    ]
