# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20190412_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivermessage',
            name='receiver_class',
        ),
        migrations.RemoveField(
            model_name='receivermessage',
            name='receiver_lesson_class',
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='group_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='组织id'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='group_type',
            field=models.IntegerField(blank=True, choices=[(1, '课程班级'), (2, '班级'), (3, '学院'), (4, '专业')], null=True, verbose_name='组织类型'),
        ),
    ]
