# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_auto_20190412_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='组织id')),
                ('group_type', models.IntegerField(blank=True, choices=[(1, '课程班级'), (2, '班级'), (3, '学院'), (4, '专业')], null=True, verbose_name='组织类型')),
                ('group_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='组织名')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_group', to='message.Message', verbose_name='消息')),
            ],
        ),
        migrations.RemoveField(
            model_name='receiverclass',
            name='cla',
        ),
        migrations.RemoveField(
            model_name='receiverclass',
            name='message',
        ),
        migrations.RemoveField(
            model_name='receiverlessonclass',
            name='lesson_class',
        ),
        migrations.RemoveField(
            model_name='receiverlessonclass',
            name='message',
        ),
        migrations.RemoveField(
            model_name='receivermessage',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='receivermessage',
            name='group_type',
        ),
        migrations.DeleteModel(
            name='ReceiverClass',
        ),
        migrations.DeleteModel(
            name='ReceiverLessonClass',
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_receive', to='message.ReceiverGroup', verbose_name='组织'),
        ),
    ]
