# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_auto_20190413_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
