# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 19:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0020_auto_20190413_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReceiverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='阅读时间')),
                ('if_delete', models.BooleanField(default=False, verbose_name='是否回收')),
                ('if_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='message.ReceiverGroup', verbose_name='组织')),
                ('receiver', models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '接收人消息',
                'verbose_name_plural': '接收人消息',
            },
        ),
        migrations.RemoveField(
            model_name='receivermessage',
            name='group',
        ),
    ]
