# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_auto_20190413_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreceivermessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_receiver_message', to='message.ReceiverGroup', verbose_name='组织'),
        ),
    ]
