# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0023_auto_20190413_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_receiver_group',
        ),
        migrations.RemoveField(
            model_name='receivergroup',
            name='message_receiver',
        ),
        migrations.AddField(
            model_name='groupreceivermessage',
            name='receiver_group',
            field=models.ForeignKey(blank=True, help_text='接收组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_receiver_message', to='message.ReceiverGroup', verbose_name='接收组'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='message.Message', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='receivergroup',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='message.Message', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='message.Message', verbose_name='消息'),
        ),
        migrations.AlterField(
            model_name='receivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
