# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0024_auto_20190413_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivergroup',
            options={'verbose_name': '消息接收组', 'verbose_name_plural': '消息接收组'},
        ),
        migrations.AlterField(
            model_name='receivergroup',
            name='group_id',
            field=models.CharField(default='', max_length=20, verbose_name='组织id'),
        ),
        migrations.AlterField(
            model_name='receivergroup',
            name='group_name',
            field=models.CharField(default='', max_length=60, verbose_name='组织名'),
        ),
        migrations.AlterUniqueTogether(
            name='messagefile',
            unique_together=set([('file', 'message')]),
        ),
        migrations.AlterUniqueTogether(
            name='receivergroup',
            unique_together=set([('message', 'group_type', 'group_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='receivermessage',
            unique_together=set([('message', 'receiver')]),
        ),
    ]
