# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0025_auto_20190415_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivergroup',
            name='group_type',
            field=models.IntegerField(choices=[(1, '课程班级'), (2, '班级'), (3, '学院'), (4, '专业')], default=1, verbose_name='组织类型'),
        ),
        migrations.AlterField(
            model_name='receivergroup',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='message.Message', verbose_name='消息'),
        ),
    ]
