# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0026_auto_20190415_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivergroup',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
