# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0028_auto_20190415_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivergroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='组织名'),
        ),
    ]
