# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0030_auto_20190415_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreceivermessage',
            name='if_report',
            field=models.BooleanField(default=False, verbose_name='是否举报'),
        ),
        migrations.AddField(
            model_name='receivermessage',
            name='if_report',
            field=models.BooleanField(default=False, verbose_name='是否举报'),
        ),
    ]
