# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0031_auto_20190416_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='report_time',
        ),
        migrations.AddField(
            model_name='message',
            name='if_report_over',
            field=models.BooleanField(default=False, verbose_name='是否被举报过度'),
        ),
    ]
