# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(default='', max_length=30)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='\u8bfe\u7a0b\u53f7')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('credit', models.IntegerField(default=2, verbose_name='\u5b66\u5206')),
                ('if_public_elective', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u516c\u9009')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='MajorLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.IntegerField(choices=[(1, '\u516c\u5171\u5fc5\u4fee'), (2, '\u5b66\u79d1\u57fa\u7840'), (3, '\u4e13\u4e1a\u4e3b\u5e72'), (4, '\u4e13\u4e1a\u4efb\u9009'), (5, '\u4e13\u4e1a\u9650\u9009')], verbose_name='\u8bfe\u7a0b\u6027\u8d28')),
                ('if_degree', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5b66\u4f4d\u8bfe\u7a0b')),
                ('major_directions', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u4fee\u65b9\u5411')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a\u57f9\u517b\u65b9\u6848\u8bfe\u7a0b',
                'verbose_name_plural': '\u4e13\u4e1a\u57f9\u517b\u65b9\u6848\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=10, verbose_name='\u6559\u5ba4')),
                ('counter', models.CharField(max_length=70, verbose_name='\u8bfe\u65f6\u7f16\u53f7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8868',
                'verbose_name_plural': '\u8bfe\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20, verbose_name='\u8bfe\u7a0b\u73ed\u7ea7\u53f7')),
                ('class_name', models.CharField(default='', max_length=30, verbose_name='\u8bfe\u7a0b\u73ed\u7ea7\u540d')),
                ('semester', models.CharField(max_length=20, verbose_name='\u5b66\u671f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8868\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b\u8868\u8bfe\u7a0b',
            },
        ),
    ]
