# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='\u6559\u5e08'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.ScheduleLesson', verbose_name='\u8bfe\u7a0b\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='majorlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson', verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='majorlesson',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Major', verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulelesson',
            unique_together=set([('class_id', 'semester', 'lesson', 'teacher')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('counter', 'schedule_lesson')]),
        ),
    ]
