# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20190324_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulelesson',
            unique_together=set([('class_id', 'semester', 'lesson')]),
        ),
    ]
