# Generated by Django 2.1.5 on 2019-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20190325_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=models.CASCADE, to='lessons.Lesson', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='majorlesson',
            name='major',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='counter',
            field=models.IntegerField(verbose_name='课时编号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_lesson',
            field=models.ForeignKey(on_delete=models.CASCADE, to='lessons.ScheduleLesson', verbose_name='课程信息'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='lesson',
            field=models.ForeignKey(on_delete=models.CASCADE, to='lessons.Lesson', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Teacher', verbose_name='教师'),
        ),
    ]
