# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20190409_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
