# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-20 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20190412_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(db_column='FId', default='', max_length=15, primary_key=True, serialize=False, verbose_name='课程号'),
        ),
    ]
