# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20190420_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='id',
            field=models.CharField(db_column='FId', max_length=20, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
