# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20190420_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
