# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190508_2244'),
        ('lessons', '0009_auto_20190420_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='admin_department',
            field=models.ForeignKey(default='57000', on_delete=django.db.models.deletion.CASCADE, to='users.Colloge', verbose_name='管理部门'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='brfore_learning_text',
            field=models.CharField(default='', help_text='先修课程说明', max_length=100, verbose_name='先修课程说明'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='profile',
            field=models.TextField(default='', help_text='课程简介', verbose_name='课程简介'),
        ),
    ]
