# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20190509_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='open_semester',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='开课学期说明'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='admin_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Colloge', verbose_name='管理部门'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='brfore_learning_text',
            field=models.CharField(blank=True, help_text='先修课程说明', max_length=100, null=True, verbose_name='先修课程说明'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='profile',
            field=models.TextField(blank=True, help_text='课程简介', null=True, verbose_name='课程简介'),
        ),
    ]
