# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20190509_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='brfore_learning_text',
            new_name='before_learning_text',
        ),
    ]
