# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20190509_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorlesson',
            name='open_semester',
            field=models.IntegerField(default=1, verbose_name='开课学期'),
        ),
    ]
