# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_majorlesson_open_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorlesson',
            name='limit_lesson_minimum_credit',
            field=models.IntegerField(blank=True, help_text='限选课最低毕业学分', null=True, verbose_name='限选课最低毕业学分'),
        ),
    ]
