# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_majorlesson_limit_lesson_minimum_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.Teacher', verbose_name='教师'),
        ),
    ]
