# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20190610_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lesson', to='users.Teacher', verbose_name='教师'),
        ),
    ]
