# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20190610_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lesson', to='lessons.Lesson', verbose_name='课程'),
        ),
    ]
