# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='2018/9/1 0:00:00', max_length=20, verbose_name='\u5b66\u671f')),
                ('algorithm', models.CharField(blank=True, max_length=35, null=True, verbose_name='\u7b97\u6cd5')),
                ('daily_score', models.FloatField(blank=True, null=True, verbose_name='\u5e73\u65f6\u6210\u7ee9')),
                ('practical_score', models.FloatField(blank=True, null=True, verbose_name='\u5b9e\u8df5\u6210\u7ee9')),
                ('theoretical_score', models.FloatField(blank=True, default=0.0, null=True, verbose_name='\u7406\u8bba\u6210\u7ee9')),
                ('score', models.FloatField(default=0.0, verbose_name='\u603b\u8bc4\u6210\u7ee9')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6700\u65b0\u6210\u7ee9',
                'verbose_name_plural': '\u6700\u65b0\u6210\u7ee9',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0.0, null=True, verbose_name='\u6210\u7ee9')),
                ('standard_score', models.FloatField(blank=True, default=-20.0, null=True, verbose_name='\u6807\u51c6\u5206')),
                ('rescore', models.FloatField(blank=True, null=True, verbose_name='\u8865\u8003\u6210\u7ee9')),
                ('if_major', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u4e13\u4e1a\u8bfe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('schedule_lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lessons.ScheduleLesson', verbose_name='\u8bfe\u8868\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u6210\u7ee9',
                'verbose_name_plural': '\u6210\u7ee9',
            },
        ),
    ]
