# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('scores', '0001_initial'),
        ('lessons', '0002_auto_20190324_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='\u5b66\u751f'),
        ),
        migrations.AddField(
            model_name='newscore',
            name='schedule_lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lessons.ScheduleLesson', verbose_name='\u8bfe\u8868\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='newscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='\u5b66\u751f'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('schedule_lesson', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='newscore',
            unique_together=set([('schedule_lesson', 'student')]),
        ),
    ]
