# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20190324_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscore',
            name='if_major',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u4e13\u4e1a\u8bfe'),
        ),
    ]
