# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190324_2054'),
        ('scores', '0003_newscore_if_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0, verbose_name='\u5df2\u4fee\u5b66\u5206')),
                ('standard_score', models.FloatField(verbose_name='\u52a0\u6743\u5e73\u5747\u6807\u51c6\u5206')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='\u5b66\u751f')),
            ],
            options={
                'verbose_name': '\u603b\u5b66\u5206',
                'verbose_name_plural': '\u603b\u5b66\u5206',
            },
        ),
    ]
