# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_totalcredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscore',
            name='semester',
        ),
    ]
