# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20190402_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcredit',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='学生'),
        ),
    ]
