# Generated by Django 2.1.5 on 2019-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20190402_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscore',
            name='schedule_lesson',
            field=models.ForeignKey(default='', on_delete=models.CASCADE, to='lessons.ScheduleLesson', verbose_name='课表课程'),
        ),
        migrations.AlterField(
            model_name='newscore',
            name='student',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='score',
            name='schedule_lesson',
            field=models.ForeignKey(default='', on_delete=models.CASCADE, to='lessons.ScheduleLesson', verbose_name='课表课程'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='totalcredit',
            name='student',
            field=models.OneToOneField(on_delete=models.CASCADE, to='users.Student', verbose_name='学生'),
        ),
    ]
