# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20190409_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='users.Student', verbose_name='学生'),
        ),
    ]
