# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_auto_20190415_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='schedule_lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='score', to='lessons.ScheduleLesson', verbose_name='课表课程'),
        ),
    ]
