# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_collect_me', to=settings.AUTH_USER_MODEL, verbose_name='好友')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_collect_friends', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏好友',
                'verbose_name_plural': '收藏好友',
            },
        ),
    ]
