# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-20 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfriends',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='collectfriends',
            name='last_talk',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上一次联系时间'),
        ),
    ]
