# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-21 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20190420_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectfriends',
            name='last_talk',
        ),
    ]
