# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-21 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_recentcontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectfriends',
            unique_together=set([('user', 'friend')]),
        ),
        migrations.AlterUniqueTogether(
            name='recentcontact',
            unique_together=set([('user', 'contact')]),
        ),
    ]
